# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts

version: 2.1

orbs:
  # Note: We are using the latest version of hello-build, whereas module B uses an older one
  module-a-hello-build: circleci/hello-build@0.0.14

jobs:
  module-a-build:
    docker:
      - image: cimg/aws:2023.03
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - common-say-hello:
          to: A
      - run: echo 'Hello world from module A! :3'
      - run: pwd
      - run: echo "current items" && ls
      - run: echo "home /project items" && ls $HOME/project
      - run: ls -lah ~/project
      - run: ls -a module-a
      - run: ls module-a/.circleci

workflows:
  module-a-workflow:
    jobs:
      - common-pre
      - module-a-build:
          requires:
            - common-pre
      - module-a-hello-build/hello-build:
          requires:
            - common-pre
